module.exports = {
  common: {
    company: 'Milkland',
    company_url: '',
  },
  home: {
    logoIcon: '/images/rtd/logo.png',
    // width: auto, height: -> reference the tailwindcss sizing  https://tailwindcss.com/docs/height
    logoSize: 'h-16 sm:h-20',
    products: [
      {
        name: 'product',
        url: '/images/rtd/pack.png',
        main: 'Ang bagong',
        subTxt: 'Milkland Multi-Grain Chocolate Drink',
      }
    ],
    buy: 'Bili na',
    introduceMain: 'Alamin ang mga mabubuting pakinabang',
    introduceSub:
      'Puno ito ng mga sustansiya tulad ng Omega 369, Vitamin B12, high in Calcium at iba pang mga vitamins at minerals na nagbibigay ng lakas ng katawan at tumutulong rin sa mental development.',
    services: [
      {
        icon:
          'M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9',
        main: 'Smart Energy',
        subTxt:
          'Tumutulong ang bagong Milkland Multi-Grain Chocolate na mapahusay ang nervous system at palakasin ang katawan para magawa ang araw-araw na mga gawain',
      },
      {
        icon:
          'M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3',
        main: 'Maraming pakinabang',
        subTxt:
          'Nagtataglay ito ng maraming benefits mula sa mga super grains (Riceberry, Brown Rice, at Oats) na may kasama pang gatas at masarap na chocolate. Masarap at masustansiyang inumin.',
      },
      {
        icon: 'M13 10V3L4 14h7v7l9-11h-7z',
        main: 'Puno ng mga bitamina',
        subTxt:
          'Nagtataglay ng Omega 369 at Vitamin B12 na good for brain. Doble ang Calcium at mas mataas sa Vitamin B1 kumpara sa ibang mga inumin.',
      },
    ],
    bottomProductArea: {
      main: 'Gusto mo na bang subukan ito?',
      subText: "Alamin kung may mabibili na sa inyong lugar",
    },
    about: {
      title: 'Tungkol sa Milkland',
      company: {
        title: 'Tungkol sa Milkland',
        text: 'Ang Milkland Multi-Grain Drink ay bagong produkto na ilalabas sa 2021 na may layuning gawin ang almusal na mas magaan, masustansiya at nakakabusog. Ang produktong ito ay sinusuri ng Lean Toolkit B.V.  kung saan ay nais sana namin malaman ang saloobin mo tungkol sa produkto para makatulong na mapabuti pa ang mga benepisyo nito. Kung maari ay magbigay ka ng feedback sa pamamagitan ng pag-click sa button sa page na ito, at pakisabi sa amin kung ano sa palagay mo ang pinakamahalagang feature ng aming produkto. Napakahalaga ng iyong feedback dahil matutulungan nito kaming ma-develop ang perpektong produkto para sa iyo sa hinaharap. Salamat!',
      },
      product: {
        title: 'Ano-ano ang mga benepisyo ng Milkland Multi-Grain Chocolate drink?',
        text: 'Ang almusal ang pinakamahalagang oras ng pagkain sa isang araw. Kaya maraming naibibigay na pakinabang ang Milkland multi-grain. Pinagsasama ng bagong produktong ito ang sarap at nutrisyon ng de-kalidad na gatas at mga butil.Dahil sa natatanging halo ng mga butil at gatas, nagbibigay ang produktong ito ng maraming benepisyo tulad ng pag-unlad ng isip, pisikal na pag-unlad, at paglakas ng katawan. Puwede para sa lahat kabilang ang maliliit na bata at nasa hustong gulang tulad mo.Sa pangkalahatan, nagbibigay ang cereal ng maraming sustansiya, bitamina, mineral, at fiber. Sa pagkain ng ceral, karaniwang kumokonsumo ka ng mas kaunting taba at kolesterol at mas maraming fiber kaya maraming pakinabang ang pag-inom ng cereal. Bukod dito, magaan at malasa ang aming cereal.',
      },
      reasons: {
        title: 'Bakit dapat mong subukan ang Milkland Multi-Grain Chocolate drink?',
        reasonList: [
          'Sagana sa Vitamin B12',
          '2x Omega 369',
          '2x Calcium',
          'Sagana sa Vitamin B1',
        ],
      },
    },
    cookie: 'Cookie statement',
    privacy: 'Privacy Statement',
    copyright: '© 2021 Lean Toolkit BV. All rights reserved.',
  },
  cookie: {
    your_own_data: 'Your own data',
  },
  privacy: {
    your_own_data: 'Your own data',
  },
  popups: [
    {
      type: 'type1',
      title: 'Magaling!',
      description: 'Anong konsepto ang mas gusto mo?',
      options: ['Masustansiya, masarap na simula ng iyong araw','Simulan ang iyong araw na may nutrisyon para sa Lakas at Talas','Tulong para lumaking matalino at malakas','Tulong para lumaking malakas at malusog','Simulan ang iyong araw na may nutrisyon ng gatas at sustansiya ng multigrains'],
      buttonTitle: 'Susunod',
    },
    {
      type: 'typeLikert',
      title: 'Gaano kahalaga para sa iyo ang sumusunod kung pinag-iisipan mong bilhin ang produktong ito?',
      likert: "Gusto ng mga anak ko ang lasa ng chocolate",
      buttonTitle: 'Susunod',
      likert_5: 'Napakahalaga',
      likert_4: 'Mahalaga',
      likert_3: 'Neutral',
      likert_2: 'Hindi mahalaga',
      likert_1: 'Talagang di-mahalaga',
    },
    {
      type: 'typeLikert',
      title: 'Gaano kahalaga para sa iyo ang sumusunod kung pinag-iisipan mong bilhin ang produktong ito?',
      likert: "Smooth inumin tulad ng ibang chocolate drink at malt drink",
      buttonTitle: 'Susunod',
      likert_5: 'Napakahalaga',
      likert_4: 'Mahalaga',
      likert_3: 'Neutral',
      likert_2: 'Hindi mahalaga',
      likert_1: 'Talagang di-mahalaga',
    },
    {
      type: 'typeLikert',
      title: 'Gaano kahalaga para sa iyo ang sumusunod kung pinag-iisipan mong bilhin ang produktong ito?',
      likert: "Dapat may cereal bits na nangunguya sa inumin",
      buttonTitle: 'Susunod',
      likert_5: 'Napakahalaga',
      likert_4: 'Mahalaga',
      likert_3: 'Neutral',
      likert_2: 'Hindi mahalaga',
      likert_1: 'Talagang di-mahalaga',
    },
    {
      type: 'typeLikert',
      title: 'Gaano kahalaga para sa iyo ang sumusunod kung pinag-iisipan mong bilhin ang produktong ito?',
      likert: "Nagbibigay ng higit na nutrisyon para sa brain development",
      buttonTitle: 'Susunod',
      likert_5: 'Napakahalaga',
      likert_4: 'Mahalaga',
      likert_3: 'Neutral',
      likert_2: 'Hindi mahalaga',
      likert_1: 'Talagang di-mahalaga',
    },
    {
      type: 'typeLikert',
      title: 'Gaano kahalaga para sa iyo ang sumusunod kung pinag-iisipan mong bilhin ang produktong ito?',
      likert: "Nagbibigay ng higit na nutrisyon para sa physical development",
      buttonTitle: 'Susunod',
      likert_5: 'Napakahalaga',
      likert_4: 'Mahalaga',
      likert_3: 'Neutral',
      likert_2: 'Hindi mahalaga',
      likert_1: 'Talagang di-mahalaga',
    },
    {
      type: 'typeLikert',
      title: 'Gaano kahalaga para sa iyo ang sumusunod kung pinag-iisipan mong bilhin ang produktong ito?',
      likert: "Nagbibigay ng higit na nutrisyong pampalakas",
      buttonTitle: 'Susunod',
      likert_5: 'Napakahalaga',
      likert_4: 'Mahalaga',
      likert_3: 'Neutral',
      likert_2: 'Hindi mahalaga',
      likert_1: 'Talagang di-mahalaga',
    },
    {
      type: 'type2',
      title: "Alamin natin kung ito ay mabibili na",
      description: 'Saan ka nakatira?',
      options: [
        'Agusan del Norte',
        'Agusan del Sur',
        'Aklan',
        'Albay',
        'Antique',
        'Apayao Abra',
        'Aurora',
        'Basilan Lanao del Sur',
        'Bataan',
        'Batanes',
        'Batangas',
        'Benguet',
        'Biliran Leyte',
        'Bohol',
        'Bukidnon',
        'Bulacan',
        'Cagayan',
        'Camarines Norte',
        'Camarines Sur',
        'Camiguin',
        'Capiz',
        'Catanduanes',
        'Cavite',
        'Cebu',
        'Compostela Valley',
        'Cotabato',
        'Davao del Norte',
        'Davao del Sur',
        'Davao Occidental',
        'Davao Oriental',
        'Dinagat Islands',
        'Eastern Samar',
        'Guimaras',
        'Ifugao',
        'Ilocos Norte',
        'Ilocos Sur',
        'Iloilo',
        'Isabela',
        'Kalinga',
        'La Union',
        'Laguna',
        'Lanao Del Norte',
        'Maguindanao',
        'Marinduque',
        'Masbate',
        'Metro Manil',
        'Misamis Occidental',
        'Misamis Oriental',
        'Mountain Province',
        'Negros Occidental',
        'Negros Oriental',
        'Northern Samar',
        'Nueva Ecija',
        'Nueva Vizcaya',
        'Occidental Mindoro',
        'Oriental Mindoro',
        'Palawan',
        'Pampanga',
        'Pangasinan',
        'Quezon',
        'Quirino',
        'Rizal',
        'Romblo',
        'Samar',
        'Sarangani',
        'Siquijor',
        'Sorsogon',
        'South Cotabato',
        'Southern Leyte',
        'Sultan Kudarat',
        'Sulu',
        'Surigao del Norte',
        'Surigao del Sur',
        'Tarlac',
        'Tawi-Taw',
        'Zambales',
        'Zamboanga Del Norte',
        'Zamboanga del Sur',
        'Zamboanga Sibuga'
      ],
      buttonTitle: 'Susunod',
    },
    {
      type: 'type3',
      title: "Paumanhin. Hindi pa mabibili ang produkto namin sa inyong lugar.",
      description:
        'Gusto mo bang subukan ang produkto kapag mabibili na ito? Kung oo, pakilagay ang email address mo sa ibaba.',
      checkText: "Nabasa ko ang Privacy Policy at sumsang-ayon ako na makontak para sa produktong ito.",
      buttonTitle: 'Paki-update ako',
    },
    {
      type: 'type4',
      title: 'Tapos na, maraming salamat!',
      description: 'Pinadalhan ka namin ng email confirmation. Ipaaalam namin sa iyo kung may balita na kami!',
      buttonTitle: 'OK',
    }
  ],
  // color class name based on tailwindcss color palette
  // https://tailwindcss.com/docs/background-color
  // https://tailwindcss.com/docs/text-color
  // https://tailwindcss.com/docs/border-color
  // https://tailwindcss.com/docs/customizing-colors
  colors: {
    main: 'bg-yellow-800',
    hover: 'bg-blue-400',
    btnText: 'text-white',
    disabled: 'bg-blue-300',
    serviceIconBG: 'bg-blue-500',
    txtMain: 'text-blue-600',
    txtSecond: 'text-blue-200',
    productTxtMain: 'text-gray-900',
    productTxtSecond: 'text-yellow-800',
    btmBG: 'bg-blue-700',
    btmBtn: 'bg-gray-50',
    btmBtnHover: 'bg-gray-100',
    btmBtnTxt: 'text-current',
    btmTxtMain: 'text-white',
    btmTxtSecond: 'text-gray-300'
  }
};
